version: '3.8'
services:
  mariadb:
    build: ./.templates/mariadb/.
    container_name: mariadb
    environment:
    - TZ=Etc/UTC
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=IOtSt4ckToorMariaDb
    - MYSQL_DATABASE=default
    - MYSQL_USER=mariadbuser
    - MYSQL_PASSWORD=IOtSt4ckmariaDbPw
    volumes:
    - ./volumes/mariadb/config:/config
    - ./volumes/mariadb/db_backup:/backup
    ports:
    - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1 

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    ports:
    - "9321:80"
    volumes:
    - ./volumes/nextcloud/html:/var/www/html
    depends_on:
    - nextcloud_db
    networks:
    - default
    - nextcloud

  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data  

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - TZ=Etc/UTC
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana
    - ./volumes/grafana/log:/var/log/grafana
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - SERVERURL=your.dynamic.dns.name
    - SERVERPORT=51820
    - PEERS=laptop,phone,tablet
    - PEERDNS=auto
    - ALLOWEDIPS=0.0.0.0/0
    ports:
    - "51820:51820/udp"
    volumes:
    - ./volumes/wireguard:/config
    - /lib/modules:/lib/modules:ro
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1

  nextcloud_db:
    container_name: nextcloud_db
    build: ./.templates/mariadb/.
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=IOtSt4ckToorMySqlDb
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    volumes:
    - ./volumes/nextcloud/db:/config
    - ./volumes/nextcloud/db_backup:/backup
    networks:
    - nextcloud

  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./volumes/mediawiki/html:/var/www/html
      - ./volumes/mediawiki/images:/var/www/html/images
      - ./volumes/mediawiki/db:/config
      - ./volumes/mediawiki/db_backup:/backup
    networks:
      - default
      - nextcloud

  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - ./volumes/moskitto/topics:/mosquitto/:rw
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
 
networks:

  default:
    driver: bridge
    ipam:
      driver: default

  nextcloud:
    driver: bridge
    internal: true
    ipam:
      driver: default

volumes:
  images:
  db: 
