version: '3.5'
services:
  myfirstserver:
    container_name: myfirstserver
    image: pythongrpc_server_myfirstserver
    build: ./.templates/myfirstserver/.
  
    volumes:
    #- /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/ping/log:/log
    
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data
    
networks:

  default:
    driver: bridge
    ipam:
      driver: default    