version: '3.9'
services:
  mariadb:
    build: ./.templates/mariadb/.
    container_name: mariadb
    environment:
    - TZ=Etc/UTC
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=IOtSt4ckToorMariaDb
    - MYSQL_DATABASE=default
    - MYSQL_USER=mariadbuser
    - MYSQL_PASSWORD=IOtSt4ckmariaDbPw
    volumes:
    - ./volumes/mariadb/config:/config
    - ./volumes/mariadb/db_backup:/backup
    ports:
    - "3306:3306"
    restart: unless-stopped
    networks:
    - default
    - network-zabbix
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1 
      
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    ports:
    - "9321:80"
    volumes:
    - ./volumes/nextcloud/html:/var/www/html
    depends_on:
    - nextcloud_db
    networks:
    - default
    - nextcloud

  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data


  mosquitto:
    container_name: mosquitto
    build:
      context: ./.templates/mosquitto/.
      args:
      - MOSQUITTO_BASE=eclipse-mosquitto:latest
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    ports:
    - "1883:1883"
    volumes:
    - ./volumes/mosquitto/config:/mosquitto/config
    - ./volumes/mosquitto/data:/mosquitto/data
    - ./volumes/mosquitto/log:/mosquitto/log
    - ./volumes/mosquitto/pwfile:/mosquitto/pwfile

  nextcloud_db:
    container_name: nextcloud_db
    build: ./.templates/mariadb/.
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=IOtSt4ckToorMySqlDb
    - MYSQL_PASSWORD=IOtSt4ckmySqlDbPw
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    volumes:
    - ./volumes/nextcloud/db:/config
    - ./volumes/nextcloud/db_backup:/backup
    networks:
    - nextcloud

  mediawiki:
    container_name: mediawiki
    image: mediawiki
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./volumes/mediawiki/html:/var/www/html
      - ./volumes/mediawiki/images:/var/www/html/images
      - ./volumes/mediawiki/db:/config
      - ./volumes/mediawiki/db_backup:/backup
    networks:
      - default
      - nextcloud

  tcpdump:
    container_name: tcpdump
    image: nicolaka/netshoot
    depends_on:
    - nginx
    command: tcpdump -i eth0 -w /data/nginx.pcap
    network_mode: service:nginx
    volumes:
    - './data:/data'

  myfirstserver:
    container_name: myfirstserver
    image: pythongrpc_server_myfirstserver
    build: ./.templates/myfirstserver/.
    restart: unless-stopped
  
    volumes:
    #- /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/ping/log:/log

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80      
    volumes:
    - ./volumes/nginx/html:/usr/share/nginx/html

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    networks:
      - network-zabbix
    links:
      - mariadb
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mariadb
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=5gc9zfs05vA0X
    depends_on:
      - mariadb
      
  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-mysql
    networks:
      - network-zabbix
    links:
      - mariadb
    restart: always
    ports:
      - "8090:8080"
      - "443:8443"
    environment:
      - ZBX_SERVER_HOST=zabbix-server     
      - DB_SERVER_HOST=mariadb
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=5gc9zfs05vA0X
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mariadb
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mariadb
      - zabbix-server
    restart: always
    ports:
      - "3000:3000"
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mariadb
      - zabbix-server
      
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2
    user: root
    networks:
    - network-zabbix
    links:
    - zabbix-server
    restart: always
    privileged: true
    volumes:
    - /var/run:/var/run
    ports:
    - "10050:10050"
    environment:
    - ZBX_HOSTNAME=Zabbix server
      #- ZBX_SERVER_HOST=172.18.0.1      
      
networks:

  default:
    driver: bridge
    ipam:
      driver: default

  nextcloud:
    driver: bridge
    internal: true
    ipam:
      driver: default

  network-zabbix:
    driver: bridge